### ISSUE TITLE
Interested to see if anyone else is experiencing a strscan dependency problem with 0.2.3

### ISSUE THREAD

**Issue by jasonperrone** [ruby/net-imap#61] opened 2022-06-09 14:45 UTC
Ruby 3.1.2 still includes strscan as a default gem. The version of strscan is 3.0.1 in Ruby 3.1.2 (latest release).
net-imap is dependent on strscan and according to the Gemspec, just wants the latest version.
strscan, the broken out gem, is now at 3.0.3, but of course is still 3.0.1 in Ruby itself. 
This is causing a gem dependency problem when trying to start a Rails app:
```
You have already activated strscan 3.0.1, but your Gemfile requires strscan 3.0.3
```

In your opinion, who is to blame here? net-imap? strscan? ruby? The Rails server (passenger, in this case)?

**Comment by bjorntrondsen** [comment] 2022-06-17 13:58
Ran into the same issue. Required a manual `gem update strscan`. 

Related discussion in
https://github.com/ruby/net-imap/pull/56

Having default gems as dependency is perhaps not such a good idea

**Comment by nevans** [comment] 2022-06-17 19:52
> according to the Gemspec, just wants the latest version

FWIW, this isn't correct.  Although your lock file may have pinned it to the latest, the `net-imap` gemspec is okay with *any* version.  See e.g: https://rubygems.org/gems/net-imap, where the dependencies explicitly states `strscan >= 0`

> In your opinion, who is to blame here? net-imap? strscan? ruby?

I'm closing this because the issue is `rubygems` -> `psych` -> `strscan`, and _I believe_ it's been fixed in `psych`.

Things to try:
1. upgrade to `psych` 4.0.4, which contains the following: https://github.com/ruby/psych/commit/3911356ec1ce5c83c0dbdf202b67d597921482e5
2. I think [the most recent relevant change to rubygems](https://github.com/rubygems/rubygems/pull/3638/commits/88478bb56945ffa9868491cacd0bc74d9d73c848) was two years ago.  Even if you already have that fix, it's probably still a good idea to try upgrading to the latest `bundler` and `rubygems_update`.
3. Edit your `Gemfile.lock` to pin the version of `strscan` that is being prematurely activated.  That should make the conflict go away.
4. You could manually add the path to your desired `strscan` to your `RUBYLIB` environment variable, so it is available before rubygems and bundler.  E.g. something like `export RUBYLIB=$(gem environment gemdir)/gems/strscan-3.0.3${RUBYLIB+:$RUBYLIB}`  (Since bundler was released, 12+ years ago, I can't remember ever needing to do this.)
5. If all else fails, [search the issues in the `rubygems` repo](https://github.com/rubygems/rubygems/search?q=strscan&type=issues) and if necessary ask for help there.

> Having default gems as dependency is perhaps not such a good idea

Although I do agree for specific cases, this is not one of those cases.  :)

**Closed by nevans** 2022-06-17 19:52 UTC
